### ISSUE TITLE
Enable pre-commit.ci on the repository

### ISSUE THREAD

**Issue by Guts** [WhereGroup/profile-manager#16]
Hi @kannes,

Since we added git hooks through pre-commit configuration, it would be convenient if you enable the pre-commit.ci integration: https://pre-commit.ci/.

Free and foss, it:

- update git hooks on a regular base (quarterly as set in the config)
- make sure that git hooks are run for every PR

**Comment by kannes** [comment]
Should be installed now

**Comment by Guts** [comment]
Thanks you!
